{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.browser",
    "module": "browser",
    "version": "1.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "browser-1.6.0.aar",
          "url": "browser-1.6.0.aar",
          "size": 218855,
          "sha512": "7fce80be9b72f92d31f39b727a2eb9f20bb2d1dae8c04426aef6c2fcff5ea03215d16e65a181ffa4754bad84c17d57459b40660e7968bb794542279a7ca3d97d",
          "sha256": "8d808fdde627949ff531a1115b2eef5e093ed312be3568c6c9ce0688c1854807",
          "sha1": "962108c8d2160d6310b4a95308c1d80a2c0401b1",
          "md5": "7118bc69fc830fe4cfc24bf99d895838"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.interpolator",
          "module": "interpolator",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "browser-1.6.0.aar",
          "url": "browser-1.6.0.aar",
          "size": 218855,
          "sha512": "7fce80be9b72f92d31f39b727a2eb9f20bb2d1dae8c04426aef6c2fcff5ea03215d16e65a181ffa4754bad84c17d57459b40660e7968bb794542279a7ca3d97d",
          "sha256": "8d808fdde627949ff531a1115b2eef5e093ed312be3568c6c9ce0688c1854807",
          "sha1": "962108c8d2160d6310b4a95308c1d80a2c0401b1",
          "md5": "7118bc69fc830fe4cfc24bf99d895838"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "browser-1.6.0-sources.jar",
          "url": "browser-1.6.0-sources.jar",
          "size": 105136,
          "sha512": "04631d53f1e076eb0af9ceab75f7c9149150287566bd55955ad0543716c276385386010a5149947b4897deedc0b3ecb776e57c911cb2aeffc76c16a061ce7bd5",
          "sha256": "b65f4610bc23e7884c71c9d583b0ebd807f4e1d198384cd2e49f0033f0979a8c",
          "sha1": "06059712f3690b2c601af9c37bd691f2a49a9588",
          "md5": "f330cf2c2cef7144edfc5c104a6cda17"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "browser-1.6.0-versionMetadata.json",
          "url": "browser-1.6.0-versionMetadata.json",
          "size": 28941,
          "sha512": "27dccfbf13a8d7f649d1d32f912b759580dff1f77aadde9bedbc60b204fb641f6517a3f7e77e34f4d9b9a7a91496eeb836d7c6567b7a895ed960e25a28fa34a2",
          "sha256": "6e259d365056fb7f665944340d02a34e907bd30ebbdeaa6c1ba8e82492d87bf8",
          "sha1": "214968509adeec2e88e995ccc1b1f1b2186c35de",
          "md5": "a2a4babba983e4812f7cf1cb9f430c6e"
        }
      ]
    }
  ]
}