{
  "formatVersion": "1.1",
  "component": {
    "url": "../../koin-core/3.4.0/koin-core-3.4.0.module",
    "group": "io.insert-koin",
    "module": "koin-core",
    "version": "3.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "koin-core-jvm-3.4.0.jar",
          "url": "koin-core-jvm-3.4.0.jar",
          "size": 430763,
          "sha512": "c6846f7b0b311813d6304f3cc397b5870fc9db6d3e3405353261bbc2d7380ec18312b61ba0e337f5775c117b93ff8195eb850e99f150ae01aaecf98c89a53a69",
          "sha256": "6fc9538fae411eadeedb1491fd694ebc633572157edb176f2b2c9f685e22993c",
          "sha1": "6cc0aace8b12422cdb9e95b95ae7e2176cce1470",
          "md5": "a5de04a2c3a7c25ab2e8ddf29d14b6b7"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "koin-core-jvm-3.4.0.jar",
          "url": "koin-core-jvm-3.4.0.jar",
          "size": 430763,
          "sha512": "c6846f7b0b311813d6304f3cc397b5870fc9db6d3e3405353261bbc2d7380ec18312b61ba0e337f5775c117b93ff8195eb850e99f150ae01aaecf98c89a53a69",
          "sha256": "6fc9538fae411eadeedb1491fd694ebc633572157edb176f2b2c9f685e22993c",
          "sha1": "6cc0aace8b12422cdb9e95b95ae7e2176cce1470",
          "md5": "a5de04a2c3a7c25ab2e8ddf29d14b6b7"
        }
      ]
    }
  ]
}
