{
  "formatVersion": "1.1",
  "component": {
    "group": "com.facebook.fresco",
    "module": "soloader",
    "version": "3.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "soloader-3.2.0.aar",
          "url": "soloader-3.2.0.aar",
          "size": 758,
          "sha512": "d07418f1bfa811bf49853de1f79d7115269a9cf0f7783a5ccb321b8fa24d7a8c97d20182883162545602eddcbc0a6ea0ffa9188fa822b3ff0ca9f3d65bc497cd",
          "sha256": "1facbda6de2afe60ddfe980dc3ab5a1c1471660c4a7311ec427c45498ac6a8cb",
          "sha1": "cc97d2ed87e488ec03f75a03af80035e6b1416b6",
          "md5": "6c6b0206075b378bce9c349de9ae1600"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.facebook.fresco",
          "module": "fbcore",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "com.facebook.soloader",
          "module": "soloader",
          "version": {
            "requires": "0.10.5"
          }
        }
      ],
      "files": [
        {
          "name": "soloader-3.2.0.aar",
          "url": "soloader-3.2.0.aar",
          "size": 758,
          "sha512": "d07418f1bfa811bf49853de1f79d7115269a9cf0f7783a5ccb321b8fa24d7a8c97d20182883162545602eddcbc0a6ea0ffa9188fa822b3ff0ca9f3d65bc497cd",
          "sha256": "1facbda6de2afe60ddfe980dc3ab5a1c1471660c4a7311ec427c45498ac6a8cb",
          "sha1": "cc97d2ed87e488ec03f75a03af80035e6b1416b6",
          "md5": "6c6b0206075b378bce9c349de9ae1600"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "soloader-3.2.0-sources.jar",
          "url": "soloader-3.2.0-sources.jar",
          "size": 1312,
          "sha512": "a51e3541c768319e9b2a75627bc6ae8e44e37bb7ba9bb0e50cdc2e0cde993c7f95ceb164112f176f3fa5ce0ef6cc5190e17c457ea2605c5b26d7c4ed63038d35",
          "sha256": "bf432ddaed4fc2060e096d198d259753636fc3ef6e2e2c4d76cc9d072192de58",
          "sha1": "0a29fa3d45405f1136ca6550b39693165e8a11b5",
          "md5": "0dd74f694ca72c45e22b469307706065"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "soloader-3.2.0-javadoc.jar",
          "url": "soloader-3.2.0-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
