{
  "formatVersion": "1.1",
  "component": {
    "group": "com.facebook.fresco",
    "module": "fresco",
    "version": "3.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.facebook.fresco",
          "module": "fbcore",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "drawee",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "imagepipeline",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "imagepipeline-native",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "memory-type-ashmem",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "memory-type-native",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "memory-type-java",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "nativeimagefilters",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "nativeimagetranscoder",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "fresco-3.2.0.aar",
          "url": "fresco-3.2.0.aar",
          "size": 39151,
          "sha512": "91e61c06d462d95d26fd429f51fa86efea16dabcb1c10e83ab6949e1d0b08e1724243a28b50fbff42f6c514f0d5de93a3d2a434b7a3b3594ac00d3876be84e09",
          "sha256": "b1056f5ea7efd4a822aa7cc899692e253ce4bdae00e68f495af21f6ce9c2529b",
          "sha1": "8af9faa52a06882695b243ee427508634a998de8",
          "md5": "6892267a70e1e2bda4c144e83a5e5fd9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.facebook.fresco",
          "module": "soloader",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "com.facebook.soloader",
          "module": "nativeloader",
          "version": {
            "requires": "0.10.5"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "ui-common",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "middleware",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "fbcore",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "drawee",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "imagepipeline",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "imagepipeline-native",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "memory-type-ashmem",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "memory-type-native",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "memory-type-java",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "nativeimagefilters",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "nativeimagetranscoder",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "fresco-3.2.0.aar",
          "url": "fresco-3.2.0.aar",
          "size": 39151,
          "sha512": "91e61c06d462d95d26fd429f51fa86efea16dabcb1c10e83ab6949e1d0b08e1724243a28b50fbff42f6c514f0d5de93a3d2a434b7a3b3594ac00d3876be84e09",
          "sha256": "b1056f5ea7efd4a822aa7cc899692e253ce4bdae00e68f495af21f6ce9c2529b",
          "sha1": "8af9faa52a06882695b243ee427508634a998de8",
          "md5": "6892267a70e1e2bda4c144e83a5e5fd9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fresco-3.2.0-sources.jar",
          "url": "fresco-3.2.0-sources.jar",
          "size": 24915,
          "sha512": "b0d303875cfa01132bece917dbe00e3c2be3f2bed0fd1b59ccb6489380173999b4bc2b4c79a07b21f1db6573d9810d177a35c48ea56874cac0aa36afdb894201",
          "sha256": "71c13c4ef3e0fa5c383935466e129822e9afebd52175060d85c6d6c8538cde56",
          "sha1": "a470ef1c7a9f3c37b41bdadbea1afe898fb13940",
          "md5": "64fac704f70f5a08de9302021316fecd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fresco-3.2.0-javadoc.jar",
          "url": "fresco-3.2.0-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
