{
  "formatVersion": "1.1",
  "component": {
    "group": "io.insert-koin",
    "module": "koin-core",
    "version": "3.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-concurrency",
          "version": {
            "requires": "1.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "koin-core-metadata-3.4.0.jar",
          "url": "koin-core-3.4.0.jar",
          "size": 45326,
          "sha512": "1fce4145ea3892d3133a5b5728bea5b8ff9f7735654960f7cd72779d57c20c76a392c2535faa3b4eca4bd44c62197f42ca256125f34df34719de2714dc9e1b15",
          "sha256": "d3dec6796e3f0a95ee4239fc000c0d66512ea452c026f263c4085348c4eb9c4a",
          "sha1": "062aa8c0070e003c13bba33e197c671f5f501814",
          "md5": "02cd3d9f7ce88aa92261d0219daf57e1"
        }
      ]
    },
    {
      "name": "iosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-iosarm32/3.4.0/koin-core-iosarm32-3.4.0.module",
        "group": "io.insert-koin",
        "module": "koin-core-iosarm32",
        "version": "3.4.0"
      }
    },
    {
      "name": "iosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-iosarm32/3.4.0/koin-core-iosarm32-3.4.0.module",
        "group": "io.insert-koin",
        "module": "koin-core-iosarm32",
        "version": "3.4.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-iosarm64/3.4.0/koin-core-iosarm64-3.4.0.module",
        "group": "io.insert-koin",
        "module": "koin-core-iosarm64",
        "version": "3.4.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-iosarm64/3.4.0/koin-core-iosarm64-3.4.0.module",
        "group": "io.insert-koin",
        "module": "koin-core-iosarm64",
        "version": "3.4.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-iossimulatorarm64/3.4.0/koin-core-iossimulatorarm64-3.4.0.module",
        "group": "io.insert-koin",
        "module": "koin-core-iossimulatorarm64",
        "version": "3.4.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-iossimulatorarm64/3.4.0/koin-core-iossimulatorarm64-3.4.0.module",
        "group": "io.insert-koin",
        "module": "koin-core-iossimulatorarm64",
        "version": "3.4.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-iosx64/3.4.0/koin-core-iosx64-3.4.0.module",
        "group": "io.insert-koin",
        "module": "koin-core-iosx64",
        "version": "3.4.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-iosx64/3.4.0/koin-core-iosx64-3.4.0.module",
        "group": "io.insert-koin",
        "module": "koin-core-iosx64",
        "version": "3.4.0"
      }
    },
    {
      "name": "jsLegacyApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../koin-core-js/3.4.0/koin-core-js-3.4.0.module",
        "group": "io.insert-koin",
        "module": "koin-core-js",
        "version": "3.4.0"
      }
    },
    {
      "name": "jsLegacyRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../koin-core-js/3.4.0/koin-core-js-3.4.0.module",
        "group": "io.insert-koin",
        "module": "koin-core-js",
        "version": "3.4.0"
      }
    },
    {
      "name": "jsIrApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../koin-core-js/3.4.0/koin-core-js-3.4.0.module",
        "group": "io.insert-koin",
        "module": "koin-core-js",
        "version": "3.4.0"
      }
    },
    {
      "name": "jsIrRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../koin-core-js/3.4.0/koin-core-js-3.4.0.module",
        "group": "io.insert-koin",
        "module": "koin-core-js",
        "version": "3.4.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../koin-core-jvm/3.4.0/koin-core-jvm-3.4.0.module",
        "group": "io.insert-koin",
        "module": "koin-core-jvm",
        "version": "3.4.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../koin-core-jvm/3.4.0/koin-core-jvm-3.4.0.module",
        "group": "io.insert-koin",
        "module": "koin-core-jvm",
        "version": "3.4.0"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-linuxx64/3.4.0/koin-core-linuxx64-3.4.0.module",
        "group": "io.insert-koin",
        "module": "koin-core-linuxx64",
        "version": "3.4.0"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-macosarm64/3.4.0/koin-core-macosarm64-3.4.0.module",
        "group": "io.insert-koin",
        "module": "koin-core-macosarm64",
        "version": "3.4.0"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-macosarm64/3.4.0/koin-core-macosarm64-3.4.0.module",
        "group": "io.insert-koin",
        "module": "koin-core-macosarm64",
        "version": "3.4.0"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-macosx64/3.4.0/koin-core-macosx64-3.4.0.module",
        "group": "io.insert-koin",
        "module": "koin-core-macosx64",
        "version": "3.4.0"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-macosx64/3.4.0/koin-core-macosx64-3.4.0.module",
        "group": "io.insert-koin",
        "module": "koin-core-macosx64",
        "version": "3.4.0"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-mingwx64/3.4.0/koin-core-mingwx64-3.4.0.module",
        "group": "io.insert-koin",
        "module": "koin-core-mingwx64",
        "version": "3.4.0"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-tvosarm64/3.4.0/koin-core-tvosarm64-3.4.0.module",
        "group": "io.insert-koin",
        "module": "koin-core-tvosarm64",
        "version": "3.4.0"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-tvosarm64/3.4.0/koin-core-tvosarm64-3.4.0.module",
        "group": "io.insert-koin",
        "module": "koin-core-tvosarm64",
        "version": "3.4.0"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-tvossimulatorarm64/3.4.0/koin-core-tvossimulatorarm64-3.4.0.module",
        "group": "io.insert-koin",
        "module": "koin-core-tvossimulatorarm64",
        "version": "3.4.0"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-tvossimulatorarm64/3.4.0/koin-core-tvossimulatorarm64-3.4.0.module",
        "group": "io.insert-koin",
        "module": "koin-core-tvossimulatorarm64",
        "version": "3.4.0"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-tvosx64/3.4.0/koin-core-tvosx64-3.4.0.module",
        "group": "io.insert-koin",
        "module": "koin-core-tvosx64",
        "version": "3.4.0"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-tvosx64/3.4.0/koin-core-tvosx64-3.4.0.module",
        "group": "io.insert-koin",
        "module": "koin-core-tvosx64",
        "version": "3.4.0"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-watchosarm32/3.4.0/koin-core-watchosarm32-3.4.0.module",
        "group": "io.insert-koin",
        "module": "koin-core-watchosarm32",
        "version": "3.4.0"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-watchosarm32/3.4.0/koin-core-watchosarm32-3.4.0.module",
        "group": "io.insert-koin",
        "module": "koin-core-watchosarm32",
        "version": "3.4.0"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-watchosarm64/3.4.0/koin-core-watchosarm64-3.4.0.module",
        "group": "io.insert-koin",
        "module": "koin-core-watchosarm64",
        "version": "3.4.0"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-watchosarm64/3.4.0/koin-core-watchosarm64-3.4.0.module",
        "group": "io.insert-koin",
        "module": "koin-core-watchosarm64",
        "version": "3.4.0"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-watchossimulatorarm64/3.4.0/koin-core-watchossimulatorarm64-3.4.0.module",
        "group": "io.insert-koin",
        "module": "koin-core-watchossimulatorarm64",
        "version": "3.4.0"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-watchossimulatorarm64/3.4.0/koin-core-watchossimulatorarm64-3.4.0.module",
        "group": "io.insert-koin",
        "module": "koin-core-watchossimulatorarm64",
        "version": "3.4.0"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-watchosx64/3.4.0/koin-core-watchosx64-3.4.0.module",
        "group": "io.insert-koin",
        "module": "koin-core-watchosx64",
        "version": "3.4.0"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-watchosx64/3.4.0/koin-core-watchosx64-3.4.0.module",
        "group": "io.insert-koin",
        "module": "koin-core-watchosx64",
        "version": "3.4.0"
      }
    },
    {
      "name": "watchosX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-watchosx86/3.4.0/koin-core-watchosx86-3.4.0.module",
        "group": "io.insert-koin",
        "module": "koin-core-watchosx86",
        "version": "3.4.0"
      }
    },
    {
      "name": "watchosX86MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-watchosx86/3.4.0/koin-core-watchosx86-3.4.0.module",
        "group": "io.insert-koin",
        "module": "koin-core-watchosx86",
        "version": "3.4.0"
      }
    }
  ]
}
