{
  "formatVersion": "1.1",
  "component": {
    "group": "com.facebook.fresco",
    "module": "animated-base",
    "version": "3.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.facebook.fresco",
          "module": "fbcore",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "imagepipeline-base",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "imagepipeline",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "imagepipeline-native",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "memory-type-ashmem",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "memory-type-native",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "memory-type-java",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "animated-drawable",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "animated-base-3.2.0.aar",
          "url": "animated-base-3.2.0.aar",
          "size": 52216,
          "sha512": "e25967ebff9721860478765b0cc74f548ab32efe404534e354802d60b03b8311674bc1dec7261dd0738a3f9d7381304fefca8bcf75d3102a5f7acfa2036543d4",
          "sha256": "10d3596b6c3a6f3640150cc7d0adc9b2eff356b7d68dbbda7c6c520ec7236730",
          "sha1": "97742e3981cba594f0a74e8a11ff98194c45676c",
          "md5": "9c2db7a8836bb9a9c007a175fd58f132"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.parse.bolts",
          "module": "bolts-tasks",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "vito-options",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "middleware",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "fbcore",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "imagepipeline-base",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "imagepipeline",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "imagepipeline-native",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "memory-type-ashmem",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "memory-type-native",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "memory-type-java",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "animated-drawable",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "animated-base-3.2.0.aar",
          "url": "animated-base-3.2.0.aar",
          "size": 52216,
          "sha512": "e25967ebff9721860478765b0cc74f548ab32efe404534e354802d60b03b8311674bc1dec7261dd0738a3f9d7381304fefca8bcf75d3102a5f7acfa2036543d4",
          "sha256": "10d3596b6c3a6f3640150cc7d0adc9b2eff356b7d68dbbda7c6c520ec7236730",
          "sha1": "97742e3981cba594f0a74e8a11ff98194c45676c",
          "md5": "9c2db7a8836bb9a9c007a175fd58f132"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "animated-base-3.2.0-sources.jar",
          "url": "animated-base-3.2.0-sources.jar",
          "size": 39625,
          "sha512": "bf124a3d0bf5ef2df183d16509ce8a1e449334324fe39e095d90e3564712dca5f46f8dc3b0daedaa58cf5cee098795cdb68e586eec7536421fb0b40890d28cf6",
          "sha256": "8430a14a7b6af2905a2ed0f691ebb2b3962518c9427e0438fc84ad331be4ee8c",
          "sha1": "323db4f3f48aa4c710e3d3b0f86466556f7480ff",
          "md5": "03ac7e6eb24500cb3de2cdfecf05567d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "animated-base-3.2.0-javadoc.jar",
          "url": "animated-base-3.2.0-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
