{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google.devtools.ksp",
    "module": "symbol-processing-common-deps",
    "version": "1.9.24-1.0.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "symbol-processing-common-deps-1.9.24-1.0.20.jar",
          "url": "symbol-processing-common-deps-1.9.24-1.0.20.jar",
          "size": 24297,
          "sha512": "a4dbba36654f4877d976766cc814641c488c5ac33b08a88333dbb87b6a11e4fd4c20c577621e02d469345c0097d0092dcdc76edf8c2f71b74ca8206426173e64",
          "sha256": "fdef6be166d642abc17fb1415c5ae363a24e0b83854cc73b51c51bdf1df506f7",
          "sha1": "e60ae41c1d8b7b2d0ab41bc901afe66dc3d0e91a",
          "md5": "407a6b331b8ad524c6e68f77e90cd211"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "symbol-processing-common-deps-1.9.24-1.0.20.jar",
          "url": "symbol-processing-common-deps-1.9.24-1.0.20.jar",
          "size": 24297,
          "sha512": "a4dbba36654f4877d976766cc814641c488c5ac33b08a88333dbb87b6a11e4fd4c20c577621e02d469345c0097d0092dcdc76edf8c2f71b74ca8206426173e64",
          "sha256": "fdef6be166d642abc17fb1415c5ae363a24e0b83854cc73b51c51bdf1df506f7",
          "sha1": "e60ae41c1d8b7b2d0ab41bc901afe66dc3d0e91a",
          "md5": "407a6b331b8ad524c6e68f77e90cd211"
        }
      ]
    }
  ]
}
